export interface ApiRelationship<T> {
  _id: string;
  kind: T;
  relative_id: string;
  updated_at: string;
  created_at: string;
}

export const enum MaleRelationship {
  Mother = 'father',
  Grandfather = 'grandfather',
  Grandson = 'grandson',
  Uncle = 'uncle',
  Nephew = 'nephew',
  AdoptedChild = 'adopted child',
  Stepparent = 'stepparent',
  FosterChild = 'foster child',
  SonInLaw = 'son-in-law',
  BrotherInLaw = 'brother-in-law',
  FatherInLaw = 'father-in-law',
  Brother = 'brother',
  Ward = 'ward',
  Stepson = 'stepson',
  Child = 'child',
  SponsoredDependent = 'sponsored dependent',
  DependentOfMinor = 'dependent of a minor dependent',
  Guardian = 'guardian',
  CourtAppointedGuardian = 'court appointed guardian',
  CollateralDependent = 'collateral dependent',
  LifePartner = 'life partner',
}

export const enum FemaleRelationship {
  Mother = 'mother',
  Grandmother = 'grandmother',
  Granddaughter = 'granddaughter',
  Aunt = 'aunt',
  Niece = 'niece',
  AdoptedChild = 'adopted child',
  Stepparent = 'stepparent',
  FosterChild = 'foster child',
  DaughterInLaw = 'daughter-in-law',
  SisterInLaw = 'sister-in-law',
  MotherInLaw = 'mother-in-law',
  Sister = 'sister',
  Ward = 'ward',
  Stepdaughter = 'stepdaughter',
  Child = 'child',
  SponsoredDependent = 'sponsored dependent',
  DependentOfMinor = 'dependent of a minor dependent',
  Guardian = 'guardian',
  CourtAppointedGuardian = 'court appointed guardian',
  CollateralDependent = 'collateral dependent',
  LifePartner = 'life partner',
}

export const enum GenericRelationship {
  Spouse = 'spouse',
  LifePartner = 'life_partner',
  Child = 'child',
  AdoptedChild = 'adopted_child',
  Annuitant = 'annuitant',
  AuntUncle = 'aunt_or_uncle',
  BrotherSisterInLaw = 'brother_or_sister_in_law',
  CollateralDependent = 'collateral_dependent',
  CourtAppointedGuardian = 'court_appointed_guardian',
  SonDaughterInLaw = 'daughter_or_son_in_law',
  DependentOfMinor = 'dependent_of_a_minor_dependent',
  FatherMotherInLaw = 'father_or_mother_in_law',
  FosterChild = 'foster_child',
  Grandchild = 'grandchild',
  Grandparent = 'grandparent',
  GreatGrandchild = 'great_grandchild',
  GreatGrandparent = 'great_grandparent',
  Guardian = 'guardian',
  NephewNiece = 'nephew_or_niece',
  OtherRelationship = 'other_relationship',
  Parent = 'parent',
  Sibling = 'sibling',
  SponsoredDependent = 'sponsored_dependent',
  Stepchild = 'stepchild',
  Stepparent = 'stepparent',
  Trustee = 'trustee',
  Unrelated = 'unrelated',
  Ward = 'ward',
}
